services:
  graphql:
    build:
      context: ./apps/graphql
      dockerfile: Dockerfile
    container_name: locker-room-graphql
    restart: unless-stopped
    ports:
      - "4001:4000"
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:secret@host.docker.internal:5432/clubhouse
      PORT: 4000
    volumes:
      - ./apps/graphql:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm run dev

